### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by nandhini673** [ghcann/COVID-19GAN#1]
Hi.. how many hours this entire model runs to generate fake samples. have you got pretrained model. can you please share the pretrained model.

**Comment by ghcann** [comment]
Hi,  

Approximately 8 hours on Colab to get to kimg 129.2, for the front_square_jpg_256_256_gray dataset. 

The link for 00001-stylegan2-front_square_jpg_256_256_gray-1gpu-config-f: 
https://drive.google.com/drive/folders/15BY-ipiWWnvLDlAJSq3H6flo4YiSaeJ3?usp=sharing 

And the link for 00021-stylegan2-02_02_varepsilon_refined-1gpu-config-f: 
https://drive.google.com/drive/folders/12fpNCADn3fn6P1gwRQ-9uE73bagWjOYq?usp=sharing

**Comment by nandhini673** [comment]
Hi,

Thanks a lot for sharing the link... Can you please tell me how to generate dataset using the pkl file.. Also the data generated are fully covid positive?

**Comment by ghcann** [comment]
No worries. On generating the dataset using the pkl file I'd recommend reading Gwern's 'Making Anime Faces With StyleGAN', https://www.gwern.net/Faces, and 'This Waifu Does Not Exist', https://www.gwern.net/TWDNE. All data is derived from the  'COVID-19 Image Data Collection' dataset, see https://arxiv.org/pdf/2003.11597.pdf.

**Comment by nandhini673** [comment]
Thanks a lot....
